services:
  postgres:
    image: postgres:16
    container_name: chat2order_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: chat2order
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d chat2order"]

  api:
    build: .

    container_name: chat2order_api

    restart: always

    ports:
      - "3000:3000"

    depends_on:
      postgres:
        condition: service_healthy

    env_file:
      - .env

    command: >
      sh -c "
        npx prisma migrate deploy &&
        node dist/server.js
      "

volumes:
  postgres_data: